const JWT_SECRET = 'ANY_SECRET_YOU_WANT';
const FACEBOOK_APP_ID = 'FACEBOOK_APP_ID_HERE';
const FACEBOOK_APP_SECRET = 'YOUR_FACEBOOK_APP_SECRET_HERE';
const MONGODB_URI = 'YOUR_MONGODB_URI_HERE';

export { JWT_SECRET, FACEBOOK_APP_ID, FACEBOOK_APP_SECRET, MONGODB_URI };